# Generated by Django 5.0.3 on 2024-06-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
