# Generated by Django 5.0.6 on 2024-06-12 18:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLS', '0002_url_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
