# Generated by Django 4.2.15 on 2024-12-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLS', '0004_totalcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalcount',
            name='click_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
