# Generated by Django 5.2.5 on 2025-08-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_links', models.PositiveIntegerField(default=0)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('active_links', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_url', models.CharField(max_length=250)),
                ('short_code', models.CharField(max_length=10)),
                ('last_created_or_used', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
